[package]
name = "blink"
version = "0.1.0"
authors = ["Michael Daffin <michael@daffin.io>"]
build = "build.rs"

[target.thumbv7em-none-eabi.dependencies.rust-libcore]
git = "https://github.com/hackndev/rust-libcore"
